# Generated by Django 5.0.7 on 2024-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Мерчант', 'verbose_name_plural': 'Мерчанты'},
        ),
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.TextField(default=0, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
