# Generated by Django 5.1 on 2024-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.TextField()),
                ('sum', models.TextField()),
                ('comment', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.TextField()),
                ('wallet', models.TextField()),
            ],
        ),
    ]
