# Generated by Django 5.0.7 on 2024-08-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.TextField()),
                ('order_id', models.TextField()),
                ('sum', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
