# Generated by Django 5.1 on 2024-08-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_pay_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
