# Generated by Django 5.0.7 on 2024-08-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
