# Generated by Django 5.1 on 2024-08-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='order_id',
        ),
    ]
